---
driver:
  name: vagrant

platforms:
  - name: centos-8
    box: centos/8
    memory: 1024
    cpus: 1

provisioner:
  name: ansible

verifier:
  name: testinfra
  options:
    v: true

scenario:
  name: default
  test_sequence:
    - lint
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - verify
    - destroy
