---
- name: Prepare
  hosts: all
  become: true
  tasks:
    - name: Upload almalinux-deploy.sh
      copy:
        src: almalinux-deploy.sh
        dest: /tmp/almalinux-deploy.sh
        owner: root
        group: root
        mode: '0700'

    - name: Upgrade all packages
      dnf:
        name: '*'
        state: latest

    - name: Reboot VM
      reboot:

    - name: Wait for reboot
      wait_for_connection:
        delay: 60
        sleep: 5
        timeout: 300
