---
- name: Install kernel-uek
  dnf:
    name: 
      - kernel-uek
    state: latest

- name: Reboot VM
  reboot:

- name: Wait for reboot
  wait_for_connection:
    delay: 60
    sleep: 5
    timeout: 300
